### ISSUE TITLE
keep a dictionary for CustomAttributes of ISynapseObject

### ISSUE THREAD

**Issue by warquys** [SynapseSL/Synapse#102]
I don't see the point of going from a dictionary to a list. I started to develop a plugin to edit the map and I use the fact that it is a dictionary and not a list. Would it be possible to keep the dictionary and not switch to a list ?
https://github.com/SynapseSL/Synapse/blob/master/Synapse/Api/CustomObjects/ISynapseObject.cs
https://github.com/SynapseSL/Synapse/blob/development/Synapse/Api/CustomObjects/ISynapseObject.cs

**Comment by GrafDimenzio** [comment]
This was changed so that it could be used in the Editor. Unity doesn't display Dictionaries in the editor

**Comment by GrafDimenzio** [comment]
Also the entire Custom Attribute system is based of this
