### ISSUE TITLE
Simplify passing delegates

### ISSUE THREAD

**Issue by AlmightyLks** [SynapseSL/Synapse#115]
https://github.com/SynapseSL/Synapse/blob/9c3d6a100abbca82131a7f53c59ef7f6334c11d2/Synapse3.SynapseModule/Events/PlayerEvents.cs#L84-L85

https://github.com/SynapseSL/Synapse/blob/9c3d6a100abbca82131a7f53c59ef7f6334c11d2/Synapse3.SynapseModule/Events/ItemEvents.cs#L46-L54

You should be able to simply pass the method group rather than creating an Action

Meaning:
```cs
 WalkOnSinkhole.Subscribe(WalkOnHazard.Raise); 
 ```
 etc.

**Comment by GrafDimenzio** [comment]
Fixed
https://github.com/SynapseSL/Synapse/commit/0f134a861f49a0eddbaef264d5caf8c3514b37a6
