### ISSUE TITLE
When I add Synapse to my server - it starts to lag a lot

### ISSUE THREAD

**Issue by MehoiL** [SynapseSL/Synapse#37]
There's a problem that I still haven't managed to fix yet. When I add your plugin to my server, it becomes so laggy and unplayable. Hope to fix the issue :)

**Comment by AlmightyLks** [comment]
Does this occur when only having Synapse installed or when using plugins?
If the latter, which plugins did you have?

**Comment by MineTech13** [comment]
> 
> 
> There's a problem that I still haven't managed to fix yet. When I add your plugin to my server, it becomes so laggy and unplayable. Hope to fix the issue :)

What do you mean by "your Plugin" Synapse is not Plugin it's a Plugin Loader
So just to be clear did you ment that if you install Synapse your server Starts to lag or tryed you to install synapse in an other loader like Exiled?

**Comment by MineTech13** [comment]
@MehoiL can you please Answer or Questions so that we can start to test and try to resolve that issue?

**Comment by MineTech13** [comment]
@GrafDimenzio You can Close this Issue
Reason: No Response
