### ISSUE TITLE
Having two permission.syml (in server-<port> and server-shared) will cause a memory leak and corrupt the file

### ISSUE THREAD

**Issue by cubuzz** [SynapseSL/Synapse#48]
Don't ask how we figured this headache out. But somehow, when having a permission.syml in both the `server-<port>` and `server-shared` will cause the YAML loader to raise errors. Yea...

This raises two issues:

- [ ] If any shared file is used, lock it - otherwise it will eventually get corrupted by two servers accessing it.
- [ ] If a file is modified, please keep a backup around.
- [ ] FOR THE LOVE OF GOD, FUCKING DON'T GIVE ME ANOTHER HEADACHE LIKE THIS. JUST CHECK FOR DUPLEXES BEFORE LOADING AND PREFER THE PRIVATE FILE (would also bring a nice feature of permission template :) )

Best regards
the person who just spent 6 hours figuring out a 60 gigabyte memory leak on a nonresponsive vm

**Comment by Mika-Westphal** [comment]
qwq
Here is the patch to prefer the non shared permissions file

[Prefer_not_shared_permissions_file.patch.txt](https://github.com/SynapseSL/Synapse/files/5978833/Prefer_not_shared_permissions_file.patch.txt)

**Comment by AlmightyLks** [comment]
>  _"[...] AND PREFER THE PRIVATE FILE"_
By private file you mean...?

**Comment by helightdev** [comment]
Preferring the port-specific permissions is a good idea, but we still have to figure out what's causing the memory-leak. Working on it

**Comment by helightdev** [comment]
Doesn't seem to be a direct framework-bug, but caused by a plugin. Enhancement ist still valid however
