### ISSUE TITLE
[CNR/QOL] "reload" will yield "Failed to reload" with no further explanation

### ISSUE THREAD

**Issue by cubuzz** [SynapseSL/Synapse#75]
s.T.
Restarting the server instead works just fine.

**Comment by GrafDimenzio** [comment]
I can't reproduce this error maybe some plugin config can't be reloaded

**Comment by cubuzz** [comment]
Spicing things up: One server *can* reload whilst the other one cannot, both are using the same config files and plugins. Perhaps it's caused by something else, underlying?

**Comment by cubuzz** [comment]
2.7.1 is properly throwing the exception, ran into that earlier. Closing.
